In [2]:
import pandas as pd

/home/franklin/anaconda3/lib/python3.8/site-packages/pandas/core/computation/expressions.py:20: UserWarning: Pandas requires version '2.7.3' or newer of 'numexpr' (version '2.7.1' currently installed).
  from pandas.core.computation.check import NUMEXPR_INSTALLED

In [3]:
output_df = pd.read_csv("ghg-emissions-by-sector.csv")

In [4]:
input_df = pd.read_csv("annual-co2-emissions.csv")

In [5]:
input_df.head()

        Entity Code  Year  Annual CO₂ emissions
0  Afghanistan  AFG  1949               14656.0
1  Afghanistan  AFG  1950               84272.0
2  Afghanistan  AFG  1951               91600.0
3  Afghanistan  AFG  1952               91600.0
4  Afghanistan  AFG  1953              106256.0

In [6]:
output_df.head()

,Entity,Code,Year,Greenhouse gas emissions from agriculture,Greenhouse gas emissions from land use change and forestry,Greenhouse gas emissions from waste,Greenhouse gas emissions from buildings,Greenhouse gas emissions from industry,Greenhouse gas emissions from manufacturing and construction,Greenhouse gas emissions from transport,Greenhouse gas emissions from electricity and heat,Fugitive emissions of greenhouse gases from energy production,Greenhouse gas emissions from other fuel combustion,Greenhouse gas emissions from bunker fuels
0,Afghanistan,AFG,1990,8069999.5,-2390000.0,1230000.0,129999.99,50000.0,570000.0,980000.0,320000.0,280000.0,0.0,20000.0
1,Afghanistan,AFG,1991,8390000.0,-2390000.0,1320000.0,140000.00,60000.0,530000.0,930000.0,300000.0,240000.0,0.0,20000.0
2,Afghanistan,AFG,1992,8400000.0,-2390000.0,1400000.0,150000.00,60000.0,390000.0,740000.0,200000.0,200000.0,0.0,20000.0
3,Afghanistan,AFG,1993,8480000.0,-2390000.0,1490000.0,160000.00,60000.0,380000.0,740000.0,200000.0,160000.0,0.0,20000.0
4,Afghanistan,AFG,1994,8520000.0,-2390000.0,1580000.0,160000.00,60000.0,360000.0,730000.0,190000.0,120000.0,0.0,20000.0

In [7]:
import pandas as pd
import requests

# Fetch the data.
df = pd.read_csv("https://ourworldindata.org/grapher/ghg-emissions-by-sector.csv?v=1&csvType=full&useColumnShortNames=false", storage_options = {'User-Agent': 'Our World In Data data fetch/1.0'})

# Fetch the metadata
metadata = requests.get("https://ourworldindata.org/grapher/ghg-emissions-by-sector.metadata.json?v=1&csvType=full&useColumnShortNames=true").json()

In [8]:
output_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6355 entries, 0 to 6354
Data columns (total 14 columns):
 #   Column                                                         Non-Null Count  Dtype
---  ------                                                         --------------  -----
 0   Entity                                                         6355 non-null   object
 1   Code                                                           6014 non-null   object
 2   Year                                                           6355 non-null   int64
 3   Greenhouse gas emissions from agriculture                      6352 non-null   float64
 4   Greenhouse gas emissions from land use change and forestry     6352 non-null   float64
 5   Greenhouse gas emissions from waste                            6293 non-null   float64
 6   Greenhouse gas emissions from buildings                        6228 non-null   float64
 7   Greenhouse gas emissions from industry                         6355 non-null   float64
 8   Greenhouse gas emissions from manufacturing and construction   6228 non-null   float64
 9   Greenhouse gas emissions from transport                        6228 non-null   float64
 10  Greenhouse gas emissions from electricity and heat             6228 non-null   float64
 11  Fugitive emissions of greenhouse gases from energy production  6293 non-null   float64
 12  Greenhouse gas emissions from other fuel combustion            6228 non-null   float64
 13  Greenhouse gas emissions from bunker fuels                     6228 non-null   float64
dtypes: float64(11), int64(1), object(2)
memory usage: 695.2+ KB

In [13]:
df.columns

Index(['Entity', 'Code', 'Year', 'Agriculture', 'Land-use change and forestry',
       'Waste', 'Buildings', 'Industry', 'Manufacturing and construction',
       'Transport', 'Electricity and heat', 'Fugitive emissions',
       'Other fuel combustion', 'Aviation and shipping'],
      dtype='object')

In [9]:
output_df['Year'].unique()

array([1990, 1991, 1992, 1993, 1994, 1995, 1996, 1997, 1998, 1999, 2000,
       2001, 2002, 2003, 2004, 2005, 2006, 2007, 2008, 2009, 2010, 2011,
       2012, 2013, 2014, 2015, 2016, 2017, 2018, 2019, 2020])

In [10]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6969 entries, 0 to 6968
Data columns (total 14 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   Entity                          6969 non-null   object
 1   Code                            6969 non-null   object
 2   Year                            6969 non-null   int64
 3   Agriculture                     6967 non-null   float64
 4   Land-use change and forestry    6967 non-null   float64
 5   Waste                           6868 non-null   float64
 6   Buildings                       6718 non-null   float64
 7   Industry                        6968 non-null   float64
 8   Manufacturing and construction  6441 non-null   float64
 9   Transport                       6884 non-null   float64
 10  Electricity and heat            6852 non-null   float64
 11  Fugitive emissions              6936 non-null   float64
 12  Other fuel combustion           6196 non-null   float64
 13  Aviation and shipping           6876 non-null   float64
dtypes: float64(11), int64(1), object(2)
memory usage: 762.4+ KB

In [14]:
df.to_csv("ghg-emissions-by-sector.csv", index=False)

In [12]:
df['Year'].unique()

array([1990, 1991, 1992, 1993, 1994, 1995, 1996, 1997, 1998, 1999, 2000,
       2001, 2002, 2003, 2004, 2005, 2006, 2007, 2008, 2009, 2010, 2011,
       2012, 2013, 2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022,
       2023])